"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, Check, CheckCircle2, ExternalLink, Pencil, Printer, RotateCcw, Save, Soup, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { CategoryCombobox } from "@/components/category-combobox";
import { deleteRecipe, getRecipe, getRecipes, Recipe, updateRecipe } from "@/lib/recipes";

const lines = (values: string[]) => values.join("\n");
const toList = (value: string) => value.split("\n").map((item) => item.replace(/^\s*(?:(?:[-•*])\s+|\d+[.)]\s+)/, "").trim()).filter(Boolean);

export function RecipeDetail({ id }: { id: string }) {
  const router = useRouter();
  const [recipe, setRecipe] = useState<Recipe | null>(null); const [edit, setEdit] = useState(false); const [status, setStatus] = useState("Memuat resep..."); const [categories, setCategories] = useState<string[]>([]);
  const [title, setTitle] = useState(""); const [category, setCategory] = useState(""); const [ingredients, setIngredients] = useState(""); const [instructions, setInstructions] = useState("");
  useEffect(() => { Promise.all([getRecipe(id), getRecipes()]).then(([current, all]) => { setRecipe(current); setCategories(all.flatMap((item) => item.categories)); if (current) { setTitle(current.title); setCategory(current.categories[0] ?? ""); setIngredients(lines(current.ingredients_list)); setInstructions(lines(current.instructions_list)); setStatus(""); } else setStatus("Resep tidak ditemukan."); }).catch(() => setStatus("Resep belum dapat dimuat.")); }, [id]);
  async function save() { if (!recipe || !title.trim()) return setStatus("Judul resep wajib diisi."); setStatus("Menyimpan perubahan..."); try { const updated = await updateRecipe(recipe.id, { title: title.trim(), categories: category ? [category] : [], ingredients_list: toList(ingredients), instructions_list: toList(instructions) }); if (updated) { setRecipe(updated); setEdit(false); setStatus("Perubahan berhasil disimpan."); } } catch { setStatus("Perubahan belum dapat disimpan."); } }
  async function toggleTried() { if (!recipe) return; setStatus("Menyimpan status resep..."); try { const updated = await updateRecipe(recipe.id, { is_tried: !recipe.is_tried }); if (updated) { setRecipe(updated); setStatus(updated.is_tried ? "Resep ditandai sudah pernah dicoba." : "Tanda sudah dicoba dibatalkan."); } } catch { setStatus("Status resep belum dapat disimpan."); } }
  async function remove() { if (!recipe || !window.confirm(`Hapus resep “${recipe.title}”? Tindakan ini tidak dapat dibatalkan.`)) return; setStatus("Menghapus resep..."); try { await deleteRecipe(recipe.id); router.push("/"); } catch { setStatus("Resep belum dapat dihapus."); } }
  if (!recipe) return <main className="grid min-h-screen place-items-center bg-[#fffaf5] p-6"><div className="text-center"><p className="text-stone-600">{status}</p><Link href="/" className="mt-4 inline-block font-semibold text-orange-700">Kembali ke koleksi</Link></div></main>;
  return <main className="min-h-screen bg-[#fffaf5]"><header className="app-navigation sticky top-0 z-10 border-b border-orange-100 bg-[#fffaf5]/95 px-4 py-4 backdrop-blur sm:px-8"><div className="mx-auto flex max-w-5xl items-center justify-between gap-3"><Link href="/" className="inline-flex items-center gap-2 text-base font-bold text-stone-700"><ArrowLeft className="h-8 w-8 md:h-4 md:w-4"/> <span className="hidden md:inline">Kembali ke koleksi</span></Link><div className="flex items-center gap-2">{!edit && <button onClick={toggleTried} className={`hidden rounded-xl px-4 py-2 text-base font-bold sm:inline-block ${recipe.is_tried ? "bg-emerald-600 text-white" : "border border-emerald-200 bg-white text-emerald-800"}`}>{recipe.is_tried ? <><RotateCcw className="mr-1.5 inline" size={16}/>Batalkan dicoba</> : <><CheckCircle2 className="mr-1.5 inline" size={16}/>Sudah dicoba</>}</button>}<button onClick={() => window.print()} aria-label="Cetak Resep" className="rounded-xl border border-stone-300 bg-white p-2.5 text-base font-bold text-stone-800 md:px-4 md:py-2"><Printer className="md:mr-1.5 inline" size={19}/><span className="hidden md:inline">Cetak Resep</span></button>{!edit ? <button onClick={() => {setEdit(true); setStatus("");}} aria-label="Edit Resep" className="rounded-xl bg-stone-900 p-2.5 text-base font-bold text-white md:px-4 md:py-2"><Pencil className="md:mr-1.5 inline" size={19}/><span className="hidden md:inline">Edit Resep</span></button> : <button onClick={save} className="rounded-xl bg-orange-600 p-2.5 text-base font-bold text-white md:px-4 md:py-2"><Save className="md:mr-1.5 inline" size={19}/><span className="hidden md:inline">Simpan Perubahan</span></button>}<button onClick={remove} aria-label="Hapus resep" className="rounded-xl border border-red-200 bg-white p-2.5 text-red-700"><Trash2 size={18}/></button></div></div></header>
    {recipe.cover_image_url ? <img src={recipe.cover_image_url} alt={`Foto ${recipe.title}`} className="recipe-cover h-auto max-h-[560px] w-full object-cover"/> : <div className="recipe-cover grid h-64 place-items-center bg-orange-100 text-orange-500"><Soup size={50}/></div>}
    <article className="recipe-print mx-auto max-w-5xl px-4 py-10 sm:px-8"><div className="recipe-content grid gap-10 lg:grid-cols-[1.4fr_.6fr]"><div className="recipe-primary"><div className="recipe-title mb-3 flex flex-wrap items-center gap-2"><p className="text-sm font-bold text-orange-700">{recipe.categories[0] || "Tanpa kategori"}</p>{recipe.is_tried && <span className="rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-bold text-emerald-800"><CheckCircle2 className="mr-1 inline" size={13}/>Sudah dicoba</span>}<button onClick={toggleTried} className="rounded-full border border-emerald-200 bg-white px-2.5 py-1 text-xs font-bold text-emerald-800 sm:hidden">{recipe.is_tried ? "Batalkan dicoba" : "Tandai sudah dicoba"}</button></div>{edit ? <><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Judul resep" className="w-full border-b-2 border-orange-300 bg-transparent pb-2 text-3xl font-black outline-none"/><div className="mt-4 max-w-sm"><CategoryCombobox value={category} onChange={setCategory} categories={categories}/></div></> : <h1 className="recipe-heading text-4xl font-black tracking-tight text-stone-950">{recipe.title}</h1>}
      {status && <p role="status" className="recipe-status mt-4 text-base text-stone-600"><Check className="mr-1 inline text-green-600" size={16}/>{status}</p>}
      {recipe.source_url && <div className="recipe-mobile-video mt-6 lg:hidden"><a href={recipe.source_url} target="_blank" rel="noreferrer" className="flex w-full items-center justify-center gap-2 rounded-xl bg-red-600 px-4 py-3 text-lg font-bold text-white hover:bg-red-700"><ExternalLink size={20}/>Tonton Video Asli</a></div>}
      <section className="recipe-ingredients mt-10"><h2 className="text-xl font-black text-stone-900">Bahan-bahan</h2>{edit ? <textarea value={ingredients} onChange={(event) => setIngredients(event.target.value)} placeholder="Satu bahan per baris" rows={Math.max(5, ingredients.split("\n").length + 1)} className="mt-3 w-full rounded-xl border border-stone-300 bg-white p-3 text-sm outline-orange-400"/> : <ul className="mt-4 space-y-3">{recipe.ingredients_list.length ? recipe.ingredients_list.map((item, index) => <li key={index} className="flex gap-3 text-stone-700"><span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-orange-500"/>{item}</li>) : <li className="text-stone-500">Bahan belum ditambahkan.</li>}</ul>}</section>
      <section className="recipe-instructions mt-10"><h2 className="text-xl font-black text-stone-900">Langkah-langkah</h2>{edit ? <textarea value={instructions} onChange={(event) => setInstructions(event.target.value)} placeholder="Satu langkah per baris" rows={Math.max(5, instructions.split("\n").length + 1)} className="mt-3 w-full rounded-xl border border-stone-300 bg-white p-3 text-sm outline-orange-400"/> : <ol className="mt-4 space-y-5">{recipe.instructions_list.length ? recipe.instructions_list.map((item, index) => <li key={index} className="flex gap-4 text-stone-700"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-orange-100 text-sm font-bold text-orange-700">{index + 1}</span><span className="pt-1">{item}</span></li>) : <li className="text-stone-500">Langkah belum ditambahkan.</li>}</ol>}</section>{recipe.source_image_url && <section className="recipe-source-image mt-10"><h2 className="text-xl font-black text-stone-900">Foto resep asli</h2><p className="mt-2 text-sm text-stone-600">Foto ditampilkan utuh sesuai proporsi unggahan.</p><img src={recipe.source_image_url} alt={`Foto resep asli ${recipe.title}`} className="mt-4 h-auto w-full rounded-2xl bg-white shadow-sm"/></section>}</div>
      <aside className="recipe-aside hidden lg:block lg:pt-12">{recipe.source_url ? <a href={recipe.source_url} target="_blank" rel="noreferrer" className="flex w-full items-center justify-center gap-2 rounded-xl bg-red-600 px-4 py-3 text-lg font-bold text-white hover:bg-red-700"><ExternalLink size={20}/>Tonton Video Asli</a> : <div className="rounded-xl bg-stone-100 p-4 text-base text-stone-600">Tidak ada tautan video asli untuk resep ini.</div>}{recipe.extracted_text && <div className="mt-5 rounded-2xl border border-orange-100 bg-white p-5"><p className="text-sm font-bold tracking-wider text-orange-700">CATATAN EKSTRAKSI</p><p className="mt-2 text-base leading-6 text-stone-600">{recipe.extracted_text}</p></div>}</aside></div></article>
  </main>;
}
